### ISSUE TITLE
Show Legends on TileLayer layers

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/jeo#11]
Currently, only layers imported from CartoDB are presenting Legends. By the moment, those layers imported from Geoserver using the TileLayer type do not show them. Geoserver is supposed to provide the Legend for a certain layer through an URL exposed by the WMS service. Example:

http://geoserver.opendevelopmentmekong.net/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=Land_Natural_Resources:map_gene_ecology
- [ ] Analyze also the risks/issues of showing different legends at the same time.
- [ ] Study the possibilities of enabling/disabling legends individually. Also, the possibility of making the legend box scrollable so legends get added in the bottom.

**Comment by acorbi** [comment]
Legends should be presented within the layer list box as in http://www.opendevelopmentcambodia.net/maps/
![bildschirmfoto 2015-06-16 um 23 09 45](https://cloud.githubusercontent.com/assets/384894/8194577/d234c624-147c-11e5-9bfd-43631fa22c05.png)

**Comment by acorbi** [comment]
@DBishton @Huyeng This is an example of how the legends can be integrated together with the explanatory text in the layer selection box.
![screenshot from 2015-06-17 16 58 41](https://cloud.githubusercontent.com/assets/384894/8210500/930c94e0-1512-11e5-91f7-eea1c8341b19.png)
![screenshot from 2015-06-17 17 00 30](https://cloud.githubusercontent.com/assets/384894/8210501/942fca40-1512-11e5-8549-9fe32d632930.png)
This approach removes any additional content from the map area thus making it more clear. However following implications should be considered, in general:
- Long texts and long legends are going to take a lot of space. My solution for this would be to add 2 toggles to the right of the layer's title: 
  1. For toggling the layer on/off
  2. For toggling between explanatory text and legend on that particular layer.
- Mappers MUST set the layer's legend within the WP Layer editing screen EVERYTIME, otherwise it won't show up. @DBishton Can we take this for granted? What is the current workflow for legends? Set them for each layer? or only for specific layer types? 

![screenshot from 2015-06-17 17 03 56](https://cloud.githubusercontent.com/assets/384894/8210563/f0d8a758-1512-11e5-9a30-d6db586f7b13.png)

**Comment by DBishton** [comment]
@acorbi Thanks, this looks like a promising solution. It does not introduce any new dependencies or changes to the workflow beyond what currently exists -- HTML needs to be inserted for each layer or will not appear.

I think your suggestion of toggling for legends and notes should resolve the space issue on this screen. Two suggestions based on your screenshots:

1) Display legend above notes, rather than the other way around 
2) Reduce font size for notes slightly

Looks great!

**Comment by acorbi** [comment]
@DBishton 1) and 2) are done

@Huyeng A suggestion for integrating the image-based legends from Geoserver is to add an <img> tag on the legend box of each post. Following this article http://docs.geoserver.org/latest/en/user/services/wms/get_legend_graphic/legendgraphic.html editors should be able to generate a valid URL to the wished image.

**Comment by acorbi** [comment]
Closing. Manual solution for this Issue and a suggestion for programatic fix available on https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/209
