### ISSUE TITLE
Remove the BetterWMS js from the parent theme

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/jeo#50]
On the parent theme don't use the BetterWMS js, but the Child theme, so the script should included into the Child theme.

**Comment by acorbi** [comment]
Hi @Huyeng good point! just to mention that the file L-TileLayer-BetterWMS.js is already on the new child theme wp-odm_theme.

**Comment by Huyeng** [comment]
You did quickly than me. :+1:
